apiVersion: v1
kind: Service
metadata:
  name: free5gc-nrf-svc
spec:
  selector:
    app: free5gc-nrf
  ports:
    - name: sbi
      protocol: TCP
      port: 29510
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-nrf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-nrf
    spec:
      containers:
      - name: myapp-container
        image: umakantk/free5gc-control-plane:b1172c3
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/nrf"]
        volumeMounts:
        - name: nrfcfg
          mountPath: /go/src/free5gc/config/nrfcfg.yaml
          subPath: nrfcfg.yaml
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.yaml
          subPath: free5GC.yaml
      volumes:
      - name: nrfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: nrfcfg.yaml
            path: nrfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.yaml
            path: free5GC.yaml
