apiVersion: v1
kind: Service
metadata:
  name: free5gc-amf-svc
spec:
  selector:
    app: free5gc-amf
  ports:
    - name: sbi
      protocol: TCP
      port: 29518
    - name: sctp
      protocol: SCTP
      port: 38412
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-amf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-amf
    spec:
      containers:
      - name: myapp-container
        image: umakantk/free5gc-control-plane:b1172c3
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/amf"]
        volumeMounts:
        - name: amfcfg
          mountPath: /go/src/free5gc/config/amfcfg.yaml
          subPath: amfcfg.yaml
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.yaml
          subPath: free5GC.yaml
      volumes:
      - name: amfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: amfcfg.yaml
            path: amfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.yaml
            path: free5GC.yaml
