apiVersion: v1
kind: Service
metadata:
  name: free5gc-smf-svc
spec:
  selector:
    app: free5gc-smf
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 29502
    - name: pfcp
      protocol: UDP
      port: 8805
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-smf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-smf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-smf
    spec:
      containers:
      - name: myapp-container
        image: umakantk/free5gc-control-plane:b1172c3
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep 30s && ./bin/smf"]
        volumeMounts:
        - name: smfcfg
          mountPath: /go/src/free5gc/config/smfcfg.yaml
          subPath: smfcfg.yaml
        - name: uerouting
          mountPath: /go/src/free5gc/config/uerouting.yaml
          subPath: uerouting.yaml
      volumes:
      - name: smfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: smfcfg.yaml
            path: smfcfg.yaml
      - name: uerouting
        configMap:
          name: free5gc-configmap
          items:
          - key: uerouting.yaml
            path: uerouting.yaml
