apiVersion: v1
kind: Service
metadata:
  name: free5gc-udr-svc
spec:
  selector:
    app: free5gc-udr
  ports:
    - name: sbi
      protocol: TCP
      port: 29504
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udr-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udr
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udr
    spec:
      containers:
      - name: myapp-container
        image: umakantk/free5gc-control-plane:b1172c3
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/udr"]
        volumeMounts:
        - name: udrcfg
          mountPath: /go/src/free5gc/config/udrcfg.conf
          subPath: udrcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: udrcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: udrcfg.conf
            path: udrcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items:
          - key: free5GC.conf
            path: free5GC.conf
