apiVersion: v1
kind: Service
metadata:
  name: free5gc-pcf-svc
spec:
  selector:
    app: free5gc-pcf
  ports:
    - name: sbi
      protocol: TCP
      port: 29507
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-pcf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-pcf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-pcf
    spec:
      containers:
      - name: myapp-container
        image: umakantk/free5gc-control-plane:b1172c3
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/pcf"]
        volumeMounts:
        - name: pcfcfg
          mountPath: /go/src/free5gc/config/pcfcfg.yaml
          subPath: pcfcfg.yaml
      volumes:
      - name: pcfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: pcfcfg.yaml
            path: pcfcfg.yaml
