apiVersion: v1
kind: Service
metadata:
  name: free5gc-udm-svc
spec:
  selector:
    app: free5gc-udm
  ports:
    - name: sbi
      protocol: TCP
      port: 29503
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-udm-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-udm
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-udm
    spec:
      containers:
      - name: myapp-container
        image: umakantk/free5gc-control-plane:b1172c3
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/udm"]
        volumeMounts:
        - name: udmcfg
          mountPath: /go/src/free5gc/config/udmcfg.yaml
          subPath: udmcfg.yaml
      volumes:
      - name: udmcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: udmcfg.yaml
            path: udmcfg.yaml
