FROM golang:1.16

RUN apt -y update
RUN apt -y install wget git iputils-ping tcpdump net-tools nano make iproute2

WORKDIR $GOPATH/src
RUN git clone --recursive -j `nproc` https://github.com/free5gc/free5gc.git
RUN cd free5gc
RUN git reset --hard b1172c3c4b9d3e1467ec1fbc349194279bc18ada
RUN git pull

WORKDIR $GOPATH/src/free5gc
RUN git checkout master
RUN git submodule sync
RUN git submodule update --init --jobs `nproc`
RUN git submodule foreach git checkout master
RUN git submodule foreach git pull --jobs `nproc`
RUN go mod download

WORKDIR $GOPATH/src/free5gc/src/test

COPY ./*.go ./

ENV GIN_MODE=release
