apiVersion: v1
kind: Service
metadata:
  name: free5gc-upf-svc
spec:
  selector:
    app: free5gc-upf
  ports:
    - name: sbi
      port: 29518
      protocol: TCP
    - name: gtp
      protocol: UDP
      port: 2152
    - name: pfcp
      protocol: UDP
      port: 8805
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-upf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-upf
    spec:
      containers:
      - name: free5gc-upf-container
        image: umakantk/free5gc-user-plane:stage3.0.5
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        # args: ["-c", "ip addr add 60.60.0.100 dev lo && ip link set dev lo up && ./bin/free5gc-upfd"]
        args: ["-c", "sleep 10s && ./bin/free5gc-upfd"]
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-volume
        - name: upfcfg
          mountPath: /go/src/free5gc/NFs/upf/build/config/upfcfg.yaml
          subPath: upfcfg.yaml
      volumes:
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: upfcfg
        configMap:
          name: free5gc-configmap
          items:
          - key: upfcfg.yaml
            path: upfcfg.yaml
